- hosts: tower
  gather_facts: no
  connection: local

  tasks:
    - name: import all project
      # ↓ https://docs.ansible.com/ansible/latest/modules/tower_receive_module.html
      tower_send:
        validate_certs: no
        tower_host: "{{ tower.host }}"
        tower_username: "{{ tower.username }}"
        tower_password: "{{ tower.password }}"
        files:
          - project_data.yml
